dist: trusty
sudo: required
language: generic
before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y cmake libdbusmenu-qt-dev gcc libqt4-dev
install:
  - mkdir build && cd ./build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ../
  - make
  - sudo make install
